language: java
jdk:
 - openjdk15

script:
- mvn clean package -Dfor-target-jre8 -DexcludedGroups=slow -Dlicense.skipDownloadLicenses=true

notifications:
 email:
   recipients:
    - travis-ci.liquibase-lsp@hohenegger.eu
   on_success: change
   on_failure: always
