language: java
jdk:
 - openjdk14

install:
- mvn clean package -Dfor-target-jre8 -DexcludedGroups="slow"

notifications:
 email:
   recipients:
    - travis-ci.liquibase-lsp@hohenegger.eu
   on_success: change
   on_failure: always
