language: java
jdk:
 - openjdk15

script:
- mvn clean package -Dfor-target-jre8 -Djupiter-exclude-tags=slow

notifications:
 email:
   recipients:
    - travis-ci.liquibase-lsp@hohenegger.eu
   on_success: change
   on_failure: always
